server:
  port: 8822
spring:
  application:
    name: bls-sso
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8810/eureka
  instance:
    prefer-ip-address: true

feign:
  httpclient:
    enabled: false # 弃用httpclient
  okhttp:
    enabled: true # 启用okhttp
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          timeoutInMilliseconds: 1000  # hystrix 超时时间

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000


