server:
  port: 8821
spring:
  application:
    name: bls-sms

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8810/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true



